FROM envoyproxy/envoy:latest

VOLUME /tmp
COPY resiliency/filtered/filtered-envoy.yaml ./etc/filtered-envoy.yaml
COPY ./resiliency/filtered/start_filtered.sh .

ENV DEBIAN_FRONTEND noninteractive

#Install Operating System
RUN  apt-get update \
  && apt-get install -y \
  software-properties-common \
  curl \
  && rm -rf /var/lib/apt/lists/*

RUN chmod +x start_filtered.sh

ENTRYPOINT ["./start_filtered.sh"]