FROM envoyproxy/envoy:latest

VOLUME /tmp
COPY resiliency/limited/limited-envoy.yaml ./etc/limited-envoy.yaml
COPY ./resiliency/limited/start_limited.sh .

ENV DEBIAN_FRONTEND noninteractive

#Install Operating System
RUN  apt-get update \
  && apt-get install -y \
  curl \
  && rm -rf /var/lib/apt/lists/*

RUN chmod +x start_limited.sh

ENTRYPOINT ["./start_limited.sh"]