FROM envoyproxy/envoy:latest

VOLUME /tmp
COPY resiliency/slow/slow-envoy.yaml ./etc/slow-envoy.yaml
COPY ./resiliency/slow/start_slow.sh .

ENV DEBIAN_FRONTEND noninteractive

#Install Operating System
RUN  apt-get update \
  && apt-get install -y \
  curl \
  && rm -rf /var/lib/apt/lists/*

RUN chmod +x start_slow.sh

ENTRYPOINT ["./start_slow.sh"]