FROM envoyproxy/envoy:latest

VOLUME /tmp
COPY ./resiliency/sidecar/sidecar-envoy.yaml ./etc/sidecar-envoy.yaml
COPY ./resiliency/sidecar/start_sidecar.sh .

ENV DEBIAN_FRONTEND noninteractive

#Install Operating System, Java and Additional Dependencies
RUN  apt-get update \
  && apt-get install -y \
  software-properties-common \
  curl \
  && rm -rf /var/lib/apt/lists/*

RUN chmod +x start_sidecar.sh

ENTRYPOINT ["./start_sidecar.sh"]